language: elixir

before_script: kerl list installations

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4.5
    - otp_release: 19.3
      elixir: 1.4.5
    - otp_release: 20.3
      elixir: 1.4.5

    - otp_release: 18.3
      elixir: 1.5.3
    - otp_release: 19.3
      elixir: 1.5.3
    - otp_release: 20.3
      elixir: 1.5.3

    - otp_release: 19.3
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.6.6
    - otp_release: 21.0
      elixir: 1.6.6
