language: elixir
elixir:
  - 1.2.2
  - 1.2.3
  - 1.2.4
  - 1.2.5
  - 1.2.6
  - 1.3.0
  - 1.3.1
  - 1.3.2
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
matrix:
  exclude:
  - elixir: 1.2.2
    otp_release: 19.0
  - elixir: 1.2.3
    otp_release: 19.0
  - elixir: 1.2.4
    otp_release: 19.0
  - elixir: 1.2.5
    otp_release: 19.0
